export const DUMMY_DATA = [
  {
    label: "The Shawshank Redemption",
    year: 1994,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Godfather",
    year: 1972,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Godfather: Part II",
    year: 1974,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Dark Knight",
    year: 2008,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "12 Angry Men",
    year: 1957,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Pulp Fiction",
    year: 1994,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Schindler's List",
    year: 1993,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Fight Club",
    year: 1999,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Forrest Gump",
    year: 1994,
    customRender: "https://picsum.photos/200",
  },
  { label: "Inception", year: 2010, customRender: "https://picsum.photos/200" },
  {
    label: "Goodfellas",
    year: 1990,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Matrix",
    year: 1999,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Seven Samurai",
    year: 1954,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "City of God",
    year: 2002,
    customRender: "https://picsum.photos/200",
  },
  { label: "Se7en", year: 1995, customRender: "https://picsum.photos/200" },
  {
    label: "The Silence of the Lambs",
    year: 1991,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "It's a Wonderful Life",
    year: 1946,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Life Is Beautiful",
    year: 1997,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Usual Suspects",
    year: 1995,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Léon: The Professional",
    year: 1994,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Spirited Away",
    year: 2001,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Saving Private Ryan",
    year: 1998,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Once Upon a Time in the West",
    year: 1968,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "American History X",
    year: 1998,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Interstellar",
    year: 2014,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Casablanca",
    year: 1942,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "City Lights",
    year: 1931,
    customRender: "https://picsum.photos/200",
  },
  { label: "Psycho", year: 1960, customRender: "https://picsum.photos/200" },
  {
    label: "The Green Mile",
    year: 1999,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Intouchables",
    year: 2011,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Modern Times",
    year: 1936,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Raiders of the Lost Ark",
    year: 1981,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Rear Window",
    year: 1954,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Pianist",
    year: 2002,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Departed",
    year: 2006,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Terminator 2: Judgment Day",
    year: 1991,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Back to the Future",
    year: 1985,
    customRender: "https://picsum.photos/200",
  },
  { label: "Whiplash", year: 2014, customRender: "https://picsum.photos/200" },
  { label: "Gladiator", year: 2000, customRender: "https://picsum.photos/200" },
  { label: "Memento", year: 2000, customRender: "https://picsum.photos/200" },
  {
    label: "The Prestige",
    year: 2006,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Lion King",
    year: 1994,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Apocalypse Now",
    year: 1979,
    customRender: "https://picsum.photos/200",
  },
  { label: "Alien", year: 1979, customRender: "https://picsum.photos/200" },
  {
    label: "Sunset Boulevard",
    year: 1950,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Great Dictator",
    year: 1940,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Cinema Paradiso",
    year: 1988,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Lives of Others",
    year: 2006,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Grave of the Fireflies",
    year: 1988,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Paths of Glory",
    year: 1957,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Django Unchained",
    year: 2012,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Shining",
    year: 1980,
    customRender: "https://picsum.photos/200",
  },
  { label: "WALL·E", year: 2008, customRender: "https://picsum.photos/200" },
  {
    label: "American Beauty",
    year: 1999,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "The Dark Knight Rises",
    year: 2012,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Princess Mononoke",
    year: 1997,
    customRender: "https://picsum.photos/200",
  },
  { label: "Aliens", year: 1986, customRender: "https://picsum.photos/200" },
  { label: "Oldboy", year: 2003, customRender: "https://picsum.photos/200" },
  {
    label: "Once Upon a Time in America",
    year: 1984,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Witness for the Prosecution",
    year: 1957,
    customRender: "https://picsum.photos/200",
  },
  { label: "Das Boot", year: 1981, customRender: "https://picsum.photos/200" },
  {
    label: "Citizen Kane",
    year: 1941,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "North by Northwest",
    year: 1959,
    customRender: "https://picsum.photos/200",
  },
  { label: "Vertigo", year: 1958, customRender: "https://picsum.photos/200" },
  {
    label: "Reservoir Dogs",
    year: 1992,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Braveheart",
    year: 1995,
    customRender: "https://picsum.photos/200",
  },
  { label: "M", year: 1931, customRender: "https://picsum.photos/200" },
  {
    label: "Requiem for a Dream",
    year: 2000,
    customRender: "https://picsum.photos/200",
  },
  { label: "Amélie", year: 2001, customRender: "https://picsum.photos/200" },
  {
    label: "A Clockwork Orange",
    year: 1971,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Like Stars on Earth",
    year: 2007,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Taxi Driver",
    year: 1976,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Lawrence of Arabia",
    year: 1962,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Double Indemnity",
    year: 1944,
    customRender: "https://picsum.photos/200",
  },
  { label: "Amadeus", year: 1984, customRender: "https://picsum.photos/200" },
  {
    label: "To Kill a Mockingbird",
    year: 1962,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Toy Story 3",
    year: 2010,
    customRender: "https://picsum.photos/200",
  },
  { label: "Logan", year: 2017, customRender: "https://picsum.photos/200" },
  {
    label: "Full Metal Jacket",
    year: 1987,
    customRender: "https://picsum.photos/200",
  },
  { label: "Dangal", year: 2016, customRender: "https://picsum.photos/200" },
  { label: "The Sting", year: 1973, customRender: "https://picsum.photos/200" },
  {
    label: "2001: A Space Odyssey",
    year: 1968,
    customRender: "https://picsum.photos/200",
  },
  {
    label: "Singin' in the Rain",
    year: 1952,
    customRender: "https://picsum.photos/200",
  },
  { label: "Toy Story", year: 1995, customRender: "https://picsum.photos/200" },
  {
    label: "Bicycle Thieves",
    year: 1948,
    customRender: "https://picsum.photos/200",
  },
  { label: "The Kid", year: 1921, customRender: "https://picsum.photos/200" },
  {
    label: "Inglourious Basterds",
    year: 2009,
    customRender: "https://picsum.photos/200",
  },
  { label: "Snatch", year: 2000, customRender: "https://picsum.photos/200" },
  { label: "3 Idiots", year: 2009, customRender: "https://picsum.photos/200" },
];
